### PR TITLE
Add UnregisterPath()

### PR DESCRIPTION
**Pull request by keep94**

### CODE REVIEW

**Comment by keep94** [comment]
I like how this has just one method, UnregisterPath. Makes things very
simple. What I don't like is calling UnregisterPath("/") on a DirectorySpec
instance invalidates that DirectorySpec instance. Clients may not expect
that and write code like this.

dirSpec, _ := RegisterDirectory("/a/directory")

dirSpec.RegisterMetric("metricA",...)
dirSpec.RegisterMetric("metricB",...)
...
dirSpec.UnregisterPath("/")
...
dirSpec.RegisterMetric("anothermetricA",...)
dirSpec.RegisterMetric("anothermetricB",...)

thinking that they are registering /a/directory/anothermetricA,
/a/directory/anothermetricB when in fact they are not!

We could panic if they try to use an unregistered DirectorySpec, but that
won't work because of multi threading and race conditions. A thread trying
to register metrics on a directorySpec could panic just because another
thread happened to remove that directorySpec at the same time.

Maybe I am concerned about nothing? thoughts?

**Comment by rgooch** [comment]
Firstly, it think it makes sense to disallow unregistering "/". Secondly, for symmetry, I think we should have UnregisterDirectory() (a DirectorySpec method with no arguments). These don't solve the problem, but make things clearer to the user. Once UnregisterDirectory() is called, any attempts to use it should cause a panic().
Note that registering a metric with a full pathname will work as always, even if an intermediate directory was unregistered, since one can do that without having to create the directory in the first place.

**Comment by keep94** [comment]
I am good with disallowing unregistering "/" and adding an
UnregisterDirectory() method.

guaranteeing panic when caller tries to use an unregistered directory
proves to be a non trivial problem for the following reasons:
1. We don't want pulling metrics to cause a panic and bring down the
   application. Because of data races, a directory could become unregistered
   while a metric pull is traversing it. In this case, we want the data pull
   to succeed just the same.
2. Caller could unregister a DirectorySpec and then call registerXXX
   methods on one of its sub directories.
3. Keeping a registered / unregistered flag with each directory adds
   additional mutable state which must be protected with a lock.

I think introducing the UnregisterDirectory() method and stating what it
does in documentation is good enough. Callers will know that
UnregisterDirectory() works like closing a file or a channel. Our goal is
to make it clear to the consumer of our API what is going on, not
necessarily prevent them from doing the wrong thing.

Just my two cents.

**Comment by rgooch** [comment]
Maybe just set the parent of a DirectorySpec to nil when you call Unregister on it?

**Comment by keep94** [comment]
Sent new pr

**Pull request merged**
