### PR TITLE
This is the implementation of the tricorder package

### PR DESCRIPTION
**Pull request by keep94**
This includes metric registration, html UI, and REST/rpc support.

### CODE REVIEW

**Comment by rgooch** [comment]
I'm approving this as-is. Changes to address the comments can come in a followup PR (Pull Request).
- instead of: func NewDistribution(bucketer *Bucketer) *Distribution
  how about: func (bucketer *Bucketer) NewDistribution() *Distribution
  what do you think?
- it would be nice to have an Add() method for a Distribution that takes a time.Duration type and does the appropriate conversions
- please add the sum to the distribution summary
- I tried NewExponentialBucketer(20, 1, 1.7) and I see buckets like:
  8.352099999999998-14.198569999999997
  this is a bit painful to read. I think we need some rounding
- a "geometric" bucketer would be nice (i.e. 1, 2, 5, 10, 20, 50, 100, 200, 500, 1000...). Perhaps:
  func NewGeometricBucketer(start, stop float64) *Bucketer
- the library built-in metrics should be under the /proc directory
- you've got the browsable, HTTP/JSON and RPC interfaces all in the browse.go file. Can this be split into 3 or 4 files (UI, JSON, RPC and maybe common components)?

**Comment by keep94** [comment]
Thanks for reviewing my changes Richard:
- Adding (bucker *Bucketer) NewDistribution() sounds good to me.
- Agreed will provide AddDuration() method for the duration type
- Agreed will add sum to distribution summary
- Do you see these hard-to-read buckets in the JSON or in the html? In the html, I attempt to convert to a float32 hoping that the template system would use fewer significant digits.
- For the geometric bucketer. How about NewGeometricBucketer(8, []float64{1.0, 2.0, 5.0}, 10.0) ==> <1, 1-2, 2-5, 5-10, 10-20, 20-50, 50-100, >100
- Will move all the built-in metrics under proc
- Yes I plan to split up browse.go file.

**Comment by rgooch** [comment]
- I saw the hard-to-read buckets in the HTML. I saw stuff like this:
  8.352099999999998-14.198569999999997
- for NewGeometricBucketer(), your API is harder to reason about the range than the approach I suggested. I do appreciate the effort to make it more general. Maybe give the range and a []float64. If the slice is nil, default to []float64{1,2,5}

**Comment by keep94** [comment]
- I will look into the buckets in HTML
- Yes I can see how letting the user provide both a slice and a multiplier makes the API easy to missuse (the caller could end up with ranges that don't make sense or worse are out of order) The default of float64{1,2,5} only makes sense for powers of 10, but maybe powers of 10 is all we need?  What if we introduce NewGeometricBucketer(-1, 2) ==> <0.1; 0.1-0.2; 0.2-0.5; 0.5-1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100

The -1 and 2 are the exponents of the lower and upper bound. Such an API would provide what most people want, but would be hard to misuse. What do you think?

**Pull request merged**
