### PR TITLE
Introduce tricorder.GetDirectory()

### PR DESCRIPTION
**Pull request by keep94**

### CODE REVIEW

**Comment by rgooch** [comment]
I think it would be cleaner to return an error code as well, with these error values:
- no entry found
- not a directory (i.e. a metric).

**Comment by keep94** [comment]
I will prepare a new PR.

**Comment by keep94** [comment]
I updated this PR so that GetDirectory() returns an error code as well to indicate no entry found vs not a directory.

**Comment by keep94** [comment]
My concern over this PR, which adds GetDirectory, is that there is complexity cost associated with adding a new function to an API. I am unsure that the GetDirectory function will pay for itself. 

Right now we have code that does this:

```
func (s *SlidingSuccessCounter) Register(path, desc string) error {
    root, _ := RegisterDirectory("/")
    return s.registerUnder(root, path, description)
}
```

The code would change to:

```
func (s *SlidingSuccessCounter) Register(path, desc string) error {
    root, _ := GetDirectory("/")
    return s.registerUnder(root, path, description)
}
```

The structure of the call site is no simpler than before.  While GetDirectory() may be useful later, I don't see a compelling use for it with the code that we have now.

**Comment by rgooch** [comment]
The GetDirectory() interface is more generic, and since the implementation is quite simple, that seems preferable to the more specific API previously proposed.

**Pull request merged**
